services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: db-system-car
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

#  catalog-mock:
#    image: typicode/json-server
#    container_name: catalog-service-mock
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./db.json:/data/db.json
#    networks:
#      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-system-car
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db-system-car
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: